from tkinter import *
window = Tk()
Label(window,text='Fullname').grid(row=0)
Label(window,text='email').grid(row=1)
Label(window,text='age').grid(row=2)
Label(window,text='Gender').grid(row=3)
e1= Entry(window)
e2= Entry(window)
e3=Entry(window)
e5=Radiobutton(window,text="male",value=0)
e4=Button(window,text='submit',width=10)
e6=Radiobutton(window,text="female",value=1)
e4=Button(window,text='submit',width=10)
e1.grid(row=0,column=1)
e2.grid(row=1,column=1)
e3.grid(row=2,column=1)
e4.grid(row=5,column=2)
e5.grid(row=3,column=1)
e6.grid(row=4,column=1)
mainloop()

